### ISSUE TITLE
"print seq" error

### ISSUE THREAD

**Issue by NathalieNeriec** [idotu/SARNAclust#1]
Hi , 

Using the given test files I run into this error: 
`$python ./SARNAclust-master/SARNAclust.py /./SARNAclust-master/GAGAandRandom.efa 2 3 "(1,0.6,10)" 9 0.6 5 0 0`
```
  File "./SARNAclust-master/SARNAclust.py", line 305
    print seq
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(seq)?

```

Any suggestions?

Thanks for any help

**Comment by idotu** [comment]
fixed
